/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cybermonkey;

import java.util.Scanner;

public class MeterConvertor {

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        System.out.println("Converting meter to miles, feet and inches: ");
        System.out.print("Metre:");

        double meters = scanner.nextDouble();

        double miles = meters * 0.0006213712;
        System.out.println(miles +  " miles");

        double feet = meters * 3.2808;
        System.out.println(feet + " feet");

        double inches = meters * 39.3701;
        System.out.println(inches + " inches");
    }
}
