/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cybermonkey;

public class BubbleSort {
    public static void main(String args[]) {
        int arr[] = {84, 32, 45, 23, 11, 22, 90, 10};
        System.out.println("Unsorted array");
        printArray(arr);
        bubbleSort(arr);

        System.out.println("Sorted array");
        printArray(arr);
    }

    private static void bubbleSort(int[] arr) {
        int n = arr.length;
        for (int i = 0; i < n - 1; i++) {
            for (int j = 0; j < n - i - 1; j++)
                if (arr[j] > arr[j + 1]) {
                    int temp = arr[j];
                    arr[j] = arr[j + 1];
                    arr[j + 1] = temp;
                }
        }
    }

    private static void printArray(int[] arr) {
        int n = arr.length;
        for (int i = 0; i < n; ++i)
            System.out.print(arr[i] + " ");
        System.out.println();
    }

}
