/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cybermonkey;

import com.google.common.primitives.Ints;

import java.util.Arrays;

public class Combine {

    public static void main(String[] args) {
        int[] a = {1, 2, 3};
        int[] b = {7, 8, 9};

        System.out.println(Arrays.toString(appendOld(a, b)));
        System.out.println(Arrays.toString(appendNew(a, b)));
        System.out.println(Arrays.toString(appendLibrary(a, b)));
    }

    public static int[] appendOld(int[] a, int[] b) {
        final int length = a.length + b.length;
        int[] c = new int[length];
        int index = 0;

        for (int i = 0; i < a.length; i++) {
            c[index] = a[i];
            index++;
        }
        for (int i = 0; i < b.length; i++) {
            c[index] = b[i];
            index++;
        }
        return c;
    }

    public static int[] appendNew(int[] a, int[] b) {
        int c[] = new int[a.length + b.length];
        System.arraycopy(a, 0, c, 0, a.length);
        System.arraycopy(b, 0, c, a.length, b.length);
        return c;
    }

    public static int[] appendLibrary(int[] a, int[] b) {
        return Ints.concat(a, b);
    }


}
