/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cybermonkey.calculator;

import static com.cybermonkey.domain.MortgageLoanMapper.calculateMortgageLoanPercentage;

public class MortgageLoanCalculator {

    public static double calculateLoanPercentage(int age, boolean isCitizen, int price, boolean isFirstBuyer) {
        return calculateMortgageLoanPercentage(age, isCitizen, price, isFirstBuyer)
                .orElseThrow( () -> new IllegalArgumentException())
                .getPercentage();
    }
}
