/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cybermonkey;

public class Main {

    public static void main(String[] args) {
        final Employee employeeJohn = new Employee("John", 7, 490);

        System.out.println(employeeJohn.getSalary());
        System.out.println(employeeJohn.getInfo());
    }
}
