/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cybermonkey;

import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class RepeatIntChecker {

    public static void main(String[] args) {
        System.out.println("Enter words, one per line.");
        Scanner in = new Scanner(System.in);
        List<Integer> numberList = new ArrayList<>();

        while (true) {
            String word = in.nextLine();
            if (word.equalsIgnoreCase("end")) {
                System.out.println("END");
                break;
            }
            final int userInt = Integer.parseInt(word);

            for (Integer number : numberList) {
                if (number == userInt) {
                    System.out.println("REPEAT");
                }
            }
            numberList.add(userInt);
        }

    }
}
