/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cybermonkey;

public class Main {

    public static void main(String[] args) {
        final Salary salary = new Salary(10000.0, "MOP");
        final Employee employeeJohn = new Employee("AE0001", "John", "Purchase", salary);

        System.out.println(employeeJohn.getSalary().getYearlyAmount());
    }
}
