/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cybermonkey;

import java.util.Random;
import java.util.Scanner;

public class GuessMe {

    public static void main(String[] args) {
        Scanner in = new Scanner(System.in);
        Random rand = new Random();

        System.out.println("Here are some problems for you to do.");
        int rightGuess = rand.nextInt(1000) + 1;
        while (true) {
            System.out.println("Please give a guess");
            int guess = in.nextInt();

            if (guess == rightGuess) {
                System.out.println("Congralutaions, Your guess is right");
                break;
            }
            if (guess > rightGuess) {
                System.out.println("Your guess is greater than the right guess");
            }
            if (guess < rightGuess) {
                System.out.println("Your guess is less than the right guess");
            }
        }
    }
}
