/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.cybermonkey;

import java.util.Scanner;

public class MarkCounts {

    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);
        String[] names = {"Tom", "Peter", "James", "Gerg", "Sara"};

        /* Read student marks. */
        int[] marks = new int[5];
        System.out.println("Enter Student marks.  Scale from 1 to 10");
        for (int i = 0; i < marks.length; i++) {
            while (true) {
                System.out.print(names[i] + ": ");
                marks[i] = input.nextInt();
                if (marks[i] <= 10) {
                    break;
                } else {
                    System.out.println("The mark you entered has been outside of the scale, please enter again.");
                }
            }
        }

        /* Display histogram of mark data. */
        System.out.println();
        for (int i = 0; i < marks.length; i++) {
            System.out.print(names[i] + "  ");
            for (int n = 0; n < marks[i]; n++) {
                System.out.print("X");
            }
            System.out.println();
        }

    }
}
